'use strict';
const assert=require('node:assert/strict'), E=require('../src/engine.js'), D=require('../src/data.js');
const {C}=D,T=E._test;let passed=0;
function test(name,fn){try{fn();passed++;console.log('✓',name);}catch(e){console.error('✗',name);throw e;}}
function battle(hero='iron',stage=1){const s=E.newRun(hero,'normal','RULES');s.run.stage=stage;E.beginBattle(s);E.mulligan(s,[]);s.battle.p.board=[];s.battle.e.board=[];s.battle.p.mana=s.battle.p.maxMana=10;s.battle.e.mana=s.battle.e.maxMana=10;s.battle.p.hand=[];s.battle.e.hand=[];s.battle.p.summoned=0;s.battle.e.summoned=0;return s;}
function hand(s,id,k='p',up=0){const c={id,uid:'test-card-'+(++s.run.nextId),up};s.battle[k].hand.push(c);return c;}
function unit(s,k,id,ready=false){const m=T.summon(s,k,id);if(ready)m.sleep=false;return m;}
function win(s){T.damage(s,'e','ehero',999,'p');T.settle(s);}

test('Card IDs, decks and all encounter references are valid',()=>{assert.equal(Object.keys(D.HEROES).length,3);assert.equal(D.BOSSES.length,8);assert.equal(Object.values(C).filter(c=>c.collect!==false).length,56);Object.values(D.HEROES).forEach(h=>{assert.equal(h.deck.length,15);h.deck.forEach(id=>assert.ok(C[id]));});D.BOSSES.forEach(b=>b.deck.forEach(id=>assert.ok(C[id])));Object.values(D.PACKS).forEach(p=>p.tiers.forEach(t=>{assert.equal(t.length,3);t.forEach(id=>assert.ok(C[id]));}));});
test('Seeded runs have deterministic card order and rewards',()=>{const a=E.newRun('grove','normal','SAME-SEED'),b=E.newRun('grove','normal','SAME-SEED');assert.deepEqual(a.battle.p.hand,b.battle.p.hand);assert.deepEqual(a.battle.e.deck,b.battle.e.deck);assert.deepEqual(T.makePacks(a),T.makePacks(b));});
test('Mulligan replaces selected cards; begins at one mana with five cards',()=>{const s=E.newRun('iron','normal','MULLIGAN-TEST');const old=s.battle.p.hand[0].uid;assert.ok(E.mulligan(s,[old]).ok);assert.equal(s.battle.p.hand.length,5);assert.equal(s.battle.p.mana,1);assert.equal(s.battle.turn,1);assert.ok(!s.battle.p.hand.slice(0,4).some(c=>c.uid===old));assert.equal(E.mulligan(s,[]).ok,false);});
test('Summoning sickness prevents newly played ordinary minions attacking',()=>{const s=battle();const m=unit(s,'p','squire');unit(s,'e','cub');assert.equal(E.canAttack(s,'p',m),false);});
test('Rush can attack minions, not the enemy hero on its summoning turn',()=>{const s=battle();const m=unit(s,'p','wolf'),e=unit(s,'e','cub');assert.deepEqual(E.attackTargets(s,'p',m),[{side:'e',id:e.uid}]);});
test('Charge can attack the hero immediately; taunt still protects the hero',()=>{const s=battle();const m=unit(s,'p','t_phoenix');assert.ok(E.attackTargets(s,'p',m).some(t=>t.id==='ehero'));const t=unit(s,'e','guard');assert.deepEqual(E.attackTargets(s,'p',m),[{side:'e',id:t.uid}]);});
test('Taunt restricts attacks but does not restrict targeted spells',()=>{const s=battle();const m=unit(s,'p','champion',true),t=unit(s,'e','guard'),c=hand(s,'bolt');assert.equal(E.attack(s,'p',m.uid,{side:'e',id:'ehero'}).ok,false);const hp=s.battle.e.hp;assert.ok(E.play(s,'p',c.uid,{side:'e',id:'ehero'}).ok);assert.equal(s.battle.e.hp,hp-2);assert.equal(t.hp,5);});
test('Combat applies both damage values, including when attacker dies',()=>{const s=battle();const p=unit(s,'p','boar',true),e=unit(s,'e','wolf');assert.ok(E.attack(s,'p',p.uid,{side:'e',id:e.uid}).ok);assert.equal(s.battle.p.board.length,0);assert.equal(s.battle.e.board.length,0);});
test('Divine shield absorbs exactly one damage instance',()=>{const s=battle();const m=unit(s,'p','iron_novice');assert.equal(T.damage(s,'p',m.uid,7,'e'),0);assert.equal(m.hp,2);assert.equal(m.shield,false);T.damage(s,'p',m.uid,1,'e');assert.equal(m.hp,1);});
test('Divine shield does not stop the protected minion dealing retaliation damage',()=>{const s=battle();const p=unit(s,'p','knight',true),e=unit(s,'e','wolf');E.attack(s,'p',p.uid,{side:'e',id:e.uid});assert.equal(p.hp,5);assert.equal(p.shield,false);assert.equal(s.battle.e.board.length,0);});
test('Normal minions attack once per turn',()=>{const s=battle();const m=unit(s,'p','cub',true);assert.ok(E.attack(s,'p',m.uid,{side:'e',id:'ehero'}).ok);assert.equal(E.attack(s,'p',m.uid,{side:'e',id:'ehero'}).ok,false);});
test('A played minion respects chosen position and buffs its two neighbors',()=>{const s=battle();const a=unit(s,'p','cub'),b=unit(s,'p','cub');const c=hand(s,'blacksmith');assert.ok(E.play(s,'p',c.uid,null,1).ok);assert.deepEqual(s.battle.p.board.map(x=>x.id),['cub','blacksmith','cub']);assert.equal(a.atk,3);assert.equal(b.hp,3);});
test('Adjacent attack aura updates immediately after banner death',()=>{const s=battle();const a=unit(s,'p','cub'),banner=unit(s,'p','banner'),b=unit(s,'p','cub'),c=unit(s,'p','cub');assert.equal(E.attackValue(s,'p',a),3);assert.equal(E.attackValue(s,'p',b),3);assert.equal(E.attackValue(s,'p',c),2);T.damage(s,'p',banner.uid,99,'e');T.settle(s);assert.equal(E.attackValue(s,'p',a),2);});
test('Board limit is seven and an invalid play does not consume the card or mana',()=>{const s=battle();for(let i=0;i<7;i++)unit(s,'p','cub');const c=hand(s,'guard'),mana=s.battle.p.mana;assert.equal(E.play(s,'p',c.uid).ok,false);assert.equal(s.battle.p.mana,mana);assert.ok(s.battle.p.hand.some(x=>x.uid===c.uid));assert.equal(T.summon(s,'p','cub'),null);});
test('All simultaneous deaths free slots before deathrattles summon',()=>{const s=battle();unit(s,'p','spider');for(let i=0;i<6;i++)unit(s,'p','cub');s.battle.p.board.slice().forEach(m=>T.damage(s,'p',m.uid,99,'e'));T.settle(s);assert.deepEqual(s.battle.p.board.map(x=>x.id),['tok_spider','tok_spider']);});
test('Simultaneous deathrattles preserve left-to-right token groups',()=>{const s=battle();const a=unit(s,'p','spider'),b=unit(s,'p','egg');unit(s,'p','guard');T.damage(s,'p',a.uid,99,'e');T.damage(s,'p',b.uid,99,'e');T.settle(s);assert.deepEqual(s.battle.p.board.map(x=>x.id),['tok_spider','tok_spider','tok_hatch','guard']);});
test('Deathrattle summons do not retrigger battlecries',()=>{const s=battle();const n=s.battle.p.hand.length;T.summon(s,'p','page');assert.equal(s.battle.p.hand.length,n);});
test('Lifesteal restores only effective damage and respects maximum health',()=>{const s=battle();s.battle.p.hp=30;const p=unit(s,'p','paladin',true),e=unit(s,'e','cub');E.attack(s,'p',p.uid,{side:'e',id:e.uid});assert.equal(s.battle.p.hp,32);});
test('Hero armor absorbs damage before health',()=>{const s=battle();s.battle.p.armor=3;const hp=s.battle.p.hp;T.damage(s,'p','phero',5,'e');assert.equal(s.battle.p.armor,0);assert.equal(s.battle.p.hp,hp-2);});
test('Healing does not over-heal heroes or minions',()=>{const s=battle();const m=unit(s,'p','cub');m.hp=1;T.heal(s,'p',m.uid,99);T.heal(s,'p','phero',99);assert.equal(m.hp,m.maxHp);assert.equal(s.battle.p.hp,s.battle.p.maxHp);});
test('Freezing skips exactly one of the target minion’s turns',()=>{const s=battle('astral');const m=unit(s,'e','ogre',true),c=hand(s,'frost');E.play(s,'p',c.uid,{side:'e',id:m.uid});E.endTurn(s,'p');assert.equal(m.frozenNow,true);assert.equal(E.canAttack(s,'e',m),false);E.endTurn(s,'e');E.endTurn(s,'p');assert.equal(m.frozenNow,false);assert.equal(E.canAttack(s,'e',m),true);});
test('Spell synergy grows a minion and once-per-turn draw triggers once',()=>{const s=battle('astral');const a=unit(s,'p','spark'),w=unit(s,'p','weaver');let c=hand(s,'bolt'),count=s.battle.p.deck.length;E.play(s,'p',c.uid,{side:'e',id:'ehero'});assert.equal(a.atk,2);assert.equal(a.hp,4);assert.equal(s.battle.p.deck.length,count-1);c=hand(s,'bolt');E.play(s,'p',c.uid,{side:'e',id:'ehero'});assert.equal(a.atk,3);assert.equal(s.battle.p.deck.length,count-1);assert.equal(w.spellCount,1);});
test('Hero powers are once-per-turn and use the right target type',()=>{for(const h of ['iron','grove','astral']){const s=battle(h),p=unit(s,'p','cub'),e=unit(s,'e','guard');const target=h==='grove'?{side:'p',id:p.uid}:h==='astral'?{side:'e',id:e.uid}:null;assert.ok(E.usePower(s,target).ok);assert.equal(E.usePower(s,target).ok,false);assert.equal(s.battle.p.mana,8);}});
test('Empty-deck fatigue increases, and excess hand draws are discarded',()=>{let s=battle();s.battle.p.deck=[];let hp=s.battle.p.hp;T.draw(s,'p',3);assert.equal(s.battle.p.hp,hp-6);assert.equal(s.battle.p.fatigue,3);s=battle();for(let i=0;i<10;i++)hand(s,'cub');const n=s.battle.p.deck.length;T.draw(s,'p');assert.equal(s.battle.p.hand.length,10);assert.equal(s.battle.p.deck.length,n-1);});
test('First-card discount and permanent upgrade stack and never go negative',()=>{const s=battle();s.run.buffs=['supply'];const a=hand(s,'bolt','p',1),b=hand(s,'squire');assert.equal(E.cardCost(s,'p',a),0);E.play(s,'p',a.uid,{side:'e',id:'ehero'});assert.equal(E.cardCost(s,'p',b),1);});
test('First summon bonuses reset on both player and enemy turns',()=>{const s=battle();s.run.buffs=['drums','hearth'];const a=unit(s,'p','cub'),b=unit(s,'p','cub');assert.equal(a.atk,3);assert.equal(a.shield,true);assert.equal(b.atk,2);assert.equal(b.shield,false);E.endTurn(s,'p');const c=unit(s,'p','cub');assert.equal(c.atk,3);assert.equal(c.shield,true);});
test('Soul echo draws at most once per global turn',()=>{const s=battle();s.run.buffs=['echo'];const a=unit(s,'p','cub'),b=unit(s,'p','cub');let count=s.battle.p.deck.length;T.damage(s,'p',a.uid,99,'e');T.damage(s,'p',b.uid,99,'e');T.settle(s);assert.equal(s.battle.p.deck.length,count-1);});
test('Treasure hourglass readies fresh/used allies and removes frozen status',()=>{const s=battle();const a=unit(s,'p','cub');a.frozenNow=true;a.freeze=1;a.attacks=1;const c=hand(s,'t_hourglass');E.play(s,'p',c.uid);assert.equal(a.shield,true);assert.equal(a.attacks,0);assert.equal(a.frozenNow,false);assert.equal(a.freeze,0);assert.ok(E.attackTargets(s,'p',a).some(t=>t.id==='ehero'));});
test('Final boss phase triggers only once, and lethal skips the phase',()=>{let s=battle('iron',8);s.battle.e.armor=0;T.damage(s,'e','ehero',29,'p');T.settle(s);assert.equal(s.battle.enraged,true);assert.equal(s.battle.e.board.length,2);T.settle(s);assert.equal(s.battle.e.board.length,2);s=battle('iron',8);win(s);assert.equal(s.screen,'reward');assert.equal(s.battle.e.board.length,0);});
test('Camp heal, removal and upgrade consume exactly one visit',()=>{for(const action of ['heal','remove','upgrade']){const s=battle();win(s);E.chooseReward(s,0);assert.equal(s.screen,'camp');const id=s.run.deck.find(c=>C[c.id].cost>0).uid,len=s.run.deck.length;s.run.hp=10;assert.ok(E.camp(s,action,id).ok);assert.equal(s.run.stage,2);assert.equal(s.screen,'battle');if(action==='heal')assert.equal(s.run.hp,20);if(action==='remove')assert.equal(s.run.deck.length,len-1);if(action==='upgrade')assert.equal(s.run.deck.find(c=>c.uid===id).up,1);assert.equal(E.camp(s,action,id).ok,false);}});
test('Full campaign awards 8 three-card packs, 2 buffs and 2 treasures, never gate 9',()=>{const s=E.newRun('grove','normal','REWARDS');for(let stage=1;stage<=8;stage++){if(s.battle.phase==='mulligan')E.mulligan(s,[]);win(s);const before=s.run.deck.length;assert.equal(s.reward.kind,'pack');assert.equal(s.reward.options.length,3);assert.ok(E.chooseReward(s,0).ok);assert.equal(s.run.deck.length,before+3);if([2,5].includes(stage)){assert.equal(s.reward.kind,'buff');E.chooseReward(s,0);}if([4,7].includes(stage)){assert.equal(s.reward.kind,'treasure');E.chooseReward(s,0);assert.equal(s.run.deck.length,before+4);}if(stage<8){assert.equal(s.screen,'camp');E.camp(s,'heal');}else assert.equal(s.screen,'victory');}assert.equal(s.run.stage,8);assert.equal(s.run.deck.length,41);assert.equal(s.run.history.length,8);assert.equal(s.run.buffs.length,2);assert.equal(s.run.treasures.length,2);assert.equal(new Set(s.run.treasures).size,2);});
test('Retry consumes one charge and restores at least 70% of max health',()=>{const s=battle();s.run.checkpointHp=2;T.damage(s,'p','phero',999,'e');T.settle(s);assert.equal(s.screen,'defeat');const retries=s.run.retries;E.retry(s);assert.equal(s.run.retries,retries-1);assert.equal(s.battle.p.hp,Math.ceil(s.run.maxHp*.7));assert.equal(s.battle.phase,'mulligan');});
test('Simultaneous hero defeats count as player defeat',()=>{const s=battle();s.battle.p.hp=0;s.battle.e.hp=0;T.settle(s);assert.equal(s.screen,'defeat');});
test('State JSON round-trip preserves deterministic next action',()=>{const s=battle('grove');unit(s,'p','cub',true);hand(s,'brood');const restored=JSON.parse(JSON.stringify(s));assert.ok(E.validateState(restored));assert.deepEqual(E.decide(s,'p'),E.decide(restored,'p'));E.execute(s,'p',E.decide(s,'p'));E.execute(restored,'p',E.decide(restored,'p'));assert.deepEqual(s,restored);assert.equal(E.validateState({version:0}),false);});
test('All 56 collectible cards can be played without exceptions and preserve limits',()=>{for(const d of Object.values(C).filter(x=>x.collect!==false)){const s=battle('astral');unit(s,'p','cub',true);unit(s,'p','spark');unit(s,'e','ogre');unit(s,'e','guard');s.battle.p.hp=18;const c=hand(s,d.id);let target=d.target?E.effectTargets(s,'p',d)[0]:null;assert.ok(E.play(s,'p',c.uid,target,1).ok,d.id);assert.ok(s.battle.p.board.length<=7,d.id);assert.ok(s.battle.p.hand.length<=10,d.id);assert.ok(E.validateState(s),d.id);}});
console.log(`\n${passed} rules tests passed.`);
